export const ROLE_PERMISSIONS: Record<string, string[]> = {
  call_center_agent: [
    'leads:read',
    'conversations:read',
    'conversations:write',
    'pipeline:read',
  ],
  call_center_manager: [
    'leads:read',
    'leads:write',
    'conversations:read',
    'conversations:write',
    'pipeline:read',
    'pipeline:write',
    'reports:read',
  ],
  marketing_staff: [
    'leads:read',
    'leads:write',
    'campaigns:read',
    'campaigns:write',
    'reports:read',
  ],
  marketing_manager: [
    'leads:read',
    'leads:write',
    'conversations:read',
    'conversations:write',
    'pipeline:read',
    'pipeline:write',
    'campaigns:read',
    'campaigns:write',
    'users:read',
    'users:write',
    'api-keys:read',
    'api-keys:write',
    'reports:read',
  ],
  super_admin: [
    'leads:read',
    'leads:write',
    'conversations:read',
    'conversations:write',
    'pipeline:read',
    'pipeline:write',
    'campaigns:read',
    'campaigns:write',
    'users:read',
    'users:write',
    'api-keys:read',
    'api-keys:write',
    'reports:read',
  ],
};
